networks:
  app-network:
    driver: bridge
services:
  # api:
  #   build: ./api
  #   restart: always
  #   ports:
  #     - 6001:6001
  #   # env_file:
  #   #   - path: .env
  #   #     required: true
  #   networks:
  #     - app-network
  #   depends_on:
  #     - mongo

  # client:
  #   build: ./client
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   # env_file:
  #   #   - path: .env
  #   #     required: false
  #   networks:
  #     - app-network
  #   depends_on:
  #     - api

  mongo:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - app-network

volumes:
  data:
